# This workflow will check the changed files for 

name: PR checker
on: [ pull_request, push ]

jobs:
  get-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.set-files.outputs.files }}
    steps:
      - uses: actions/checkout@v2
      - name: Installing jq
        run: |
            apt update && apt install sudo
            sudo apt update -y
            sudo apt install jq -y
      - id: set-files 
        run: |
            # URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
            # echo $URL
            URL="https://api.github.com/repos/tt-le/guide-getting-started/pulls/1/files"
            FILES=$(curl -s -X GET -G $URL| jq -r '[ .[] |  .filename ]' | tr -d '\n')
            echo $FILES
            echo "::set-output name=files::$FILES"
  check-files:
      runs-on: ubuntu-latest
      needs: get-files
      strategy:
        matrix:
          files: ${{ fromJSON(needs.get-files.outputs.files) }}
      steps:
          - uses: actions/checkout@v2
          - name: Checker
            run: |
                echo ${{ matrix.files }}
                ls
                chmod +x ./scripts/check-license.sh
                sh ./scripts/check-license.sh ${{ matrix.files }}
  compare-directories:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: compare start to finish
            run: |
                # compare !
  
