name: Daily Build
 
# Triggers the workflow on push events but only for the master branch.
on:
  push:
    branches:
      - master
      - main
      - qa
  pull_request:
    branches:
      - master
      - main
      - qa

jobs:
  Master:
    name: Build and test
    runs-on: ubuntu-latest
      
    steps:
        
      # Any prerequisite steps
      - uses: actions/checkout@master
      
      - name: Run build
        id: build
        run: |
          cp $GITHUB_WORKSPACE/.github/workflows/mavenTest.sh $GITHUB_WORKSPACE/finish
          cp $GITHUB_WORKSPACE/.github/workflows/dockerTest.sh $GITHUB_WORKSPACE/finish
          cd $GITHUB_WORKSPACE/finish
          bash mavenTest.sh
          bash dockerTest.sh